## 꺾기

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
칼럼 =['연번','자치구','담당','구분','집행일시','시분값', \
       '집행장소','집행주소','결재방법','집행금액','집행목적/집행내역/내용','대상인원','50만원이상 결재시 증빙서류','비고']
기본경로 = r'C:\Users\user\1코드들\2018년_정공센_알권리감시단_업무추진비_코드\Files\공개자료_업데이트\\'
파일위치경로 = r'C:/Users/user/Desktop/구청별 업무추진비(엑셀)/'
구청목록 = [ 
    '종로구','중구','용산구','성동구','광진구','동대문구','중랑구','성북구','강북구','도봉구','노원구',
    '은평구','서대문구','마포구','양천구','강서구','구로구','금천구','영등포구','동작구','관악구','서초구',
    '강남구','송파구','강동구','서울특별시'
            ]   #26개
요일 = {'Monday':'월', 'Tuesday':'화', 'Wednesday':'수', 'Thursday':'목', 'Friday':'금', 'Saturday':'토', 'Sunday':'일'}
일정시점_이후 = '2014-07-01'

In [3]:
구청별=dict()

for 구청이름 in 구청목록:
    try:
        임시 = pd.read_excel(파일위치경로+구청이름+'(정제).xlsx')
        임시 = 임시[임시['집행일시']>=일정시점_이후]
        구청별[구청이름] = 임시
    except FileNotFoundError:
        print('파일이 없습니다:'+구청이름)
    except :
        print(구청이름)

파일이 없습니다:서울특별시

In [52]:
구청별['도봉구'].sort_values('집행일시')

,자치구,담당,구분,집행일시,시분값,집행장소,집행주소,결재방법,집행금액,집행목/집행내역/내용,대상인원,50만원이상 결재시 증빙서류,비고,요일
42,도봉구,NaN,의장,2014-07-09 00:00:00,13:38:27,NaN,NaN,카드,618000,의원 및 의회직원등 간담회,30,NaN,NaN,수
110,도봉구,NaN,부의장,2014-07-09 00:00:00,19:53:50,NaN,NaN,카드,14000,여성의원 간담회,4,NaN,NaN,수
109,도봉구,NaN,부의장,2014-07-09 00:00:00,19:30:54,NaN,NaN,카드,136000,유관기관 직원 간담회,10,NaN,NaN,수
44,도봉구,NaN,의장,2014-07-09 00:00:00,12:53:25,NaN,NaN,카드,84000,의회직원등 간담회,5,NaN,NaN,수
43,도봉구,NaN,의장,2014-07-09 00:00:00,20:39:47,NaN,NaN,카드,385000,의원 및 의회직원등 간담회,15,NaN,NaN,수
111,도봉구,NaN,부의장,2014-07-10 00:00:00,20:29:22,NaN,NaN,카드,75000,유관기관 직원 간담회,7,NaN,NaN,목
45,도봉구,NaN,의장,2014-07-11 00:00:00,13:07:57,NaN,NaN,카드,117000,여성의원과 간담회,6,NaN,NaN,금
112,도봉구,NaN,부의장,2014-07-11 00:00:00,12:54:50,NaN,NaN,카드,57500,여성의원 간담회,6,NaN,NaN,금
113,도봉구,NaN,부의장,2014-07-13 00:00:00,19:07:23,NaN,NaN,카드,72000,의원 및 의회직원등 간담회,6,NaN,NaN,일
46,도봉구,NaN,의장,2014-07-14 00:00:00,12:39:32,NaN,NaN,카드,290000,구청직원과 간담회,12,NaN,NaN,월
114,도봉구,NaN,부의장,2014-07-14 00:00:00,18:36:23,NaN,NaN,카드,68000,여성의원등 간담회,8,NaN,NaN,월
47,도봉구,NaN,의장,2014-07-15 00:00:00,20:15:13,NaN,NaN,카드,304000,의원 및 의회직원등 간담회,15,NaN,NaN,화
48,도봉구,NaN,의장,2014-07-16 00:00:00,19:52:09,NaN,NaN,카드,480000,의원 및 의회직원등 간담회,20,NaN,NaN,수
49,도봉구,NaN,의장,2014-07-16 00:00:00,12:46:39,NaN,NaN,카드,75000,여성의원과 간담회,5,NaN,NaN,수
151,도봉구,NaN,운영위원장,2014-07-16 00:00:00,12:33:56,NaN,NaN,카드,278800,의원 및 의회직원 간담회,11,NaN,NaN,수
152,도봉구,NaN,운영위원장,2014-07-17 00:00:00,18:36:04,NaN,NaN,카드,43000,운영위의원 간담회,4,NaN,NaN,목
214,도봉구,NaN,재무건설위원장,2014-07-17 00:00:00,20:34:25,NaN,NaN,카드,95000,재무건설위원회 의원 간담회,6,NaN,NaN,목
184,도봉구,NaN,행정복지위원장,2014-07-17 00:00:00,21:39:56,NaN,NaN,카드,34000,구청직원과 간담회,3,NaN,NaN,목
50,도봉구,NaN,의장,2014-07-17 00:00:00,19:49:48,NaN,NaN,카드,143000,구청직원과 간담회,7,NaN,NaN,목
51,도봉구,NaN,의장,2014-07-18 00:00:00,20:21:10,NaN,NaN,카드,179990,구청직원과 간담회,8,NaN,NaN,금
52,도봉구,NaN,의장,2014-07-18 00:00:00,13:43:27,NaN,NaN,카드,95000,여성의원과 간담회,5,NaN,NaN,금
115,도봉구,NaN,부의장,2014-07-18 00:00:00,13:09:07,NaN,NaN,카드,54000,구청직원과 간담회,4,NaN,NaN,금
116,도봉구,NaN,부의장,2014-07-19 00:00:00,17:01:29,NaN,NaN,카드,38500,유관기관직원 간담회,5,NaN,NaN,토
153,도봉구,NaN,운영위원장,2014-07-20 00:00:00,21:12:31,NaN,NaN,카드,105000,제239회임시회관련 운영회의원등 간담회,4,NaN,NaN,일
53,도봉구,NaN,의장,2014-07-21 00:00:00,20:14:31,NaN,NaN,카드,77000,제239회 임시회관련 의원 간담회,5,NaN,NaN,월
185,도봉구,NaN,행정복지위원장,2014-07-21 00:00:00,21:34:15,NaN,NaN,카드,75000,유관기관직원 간담회,5,NaN,NaN,월
215,도봉구,NaN,재무건설위원장,2014-07-21 00:00:00,18:21:12,NaN,NaN,카드,147000,재무건설위원회 의원 간담회,10,NaN,NaN,월
54,도봉구,NaN,의장,2014-07-22 00:00:00,13:57:47,NaN,NaN,카드,210000,제239회 임시회관련 상임위원장 및 의회직원 간담회,10,NaN,NaN,화
187,도봉구,NaN,행정복지위원장,2014-07-22 00:00:00,17:41:36,NaN,NaN,카드,20500,여성의원 간담회,5,NaN,NaN,화
186,도봉구,NaN,행정복지위원장,2014-07-22 00:00:00,16:00:46,NaN,NaN,카드,128000,유관기관직원 간담회,6,NaN,NaN,화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3108,도봉구,NaN,부의장,2018-02-19 00:00:00,17:44:17,NaN,NaN,카드,185000,의정 정보교류 소요경비,7,NaN,NaN,월
3062,도봉구,NaN,의장,2018-02-19 00:00:00,12:30:22,NaN,NaN,카드,32000,의정활동 및 직무수행 소요경비,4,NaN,NaN,월
3203,도봉구,NaN,복지건설위원장,2018-02-19 00:00:00,21:20:50,NaN,NaN,카드,22000,의정활동 및 직무수행 소요경비,2,NaN,NaN,월
3064,도봉구,NaN,의장,2018-02-20 00:00:00,19:55:50,NaN,NaN,카드,150000,의정 정보교류 소요경비,7,NaN,NaN,화
3187,도봉구,NaN,복지건설위원장,2018-02-20 00:00:00,20:57:20,NaN,NaN,카드,54000,의정활동 및 직무수행 소요경비,3,NaN,NaN,화
3147,도봉구,NaN,행정기획위원장,2018-02-20 00:00:00,12:10:27,NaN,NaN,카드,208000,의정 정보교류 소요경비,7,NaN,NaN,화
3109,도봉구,NaN,부의장,2018-02-21 00:00:00,12:45:39,NaN,NaN,카드,100000,도봉뉴스 자료 게재 관련 간담회,4,NaN,NaN,수
3206,도봉구,NaN,복지건설위원장,2018-02-22 00:00:00,12:57:23,NaN,NaN,카드,19000,의정활동 및 직무수행 소요경비,2,NaN,NaN,목
3164,도봉구,NaN,행정기획위원장,2018-02-22 00:00:00,14:08:34,NaN,NaN,카드,123000,창동역 노점 개선사항 논의 관련 간담회,5,NaN,NaN,목
3145,도봉구,NaN,운영위원장,2018-02-22 00:00:00,13:36:22,NaN,NaN,카드,200000,의정 정보교류 소요경비,7,NaN,NaN,목
3065,도봉구,NaN,의장,2018-02-23 00:00:00,18:44:41,NaN,NaN,카드,126000,2018년 지방의회 알기 체험학습 프로그램 운영계획 수립에 따른 간담회,5,NaN,NaN,금
3191,도봉구,NaN,운영위원장,2018-02-23 00:00:00,13:32:00,NaN,NaN,카드,44400,의정활동 및 직무수행 소요경비,2,NaN,NaN,금
3110,도봉구,NaN,부의장,2018-02-23 00:00:00,13:48:39,NaN,NaN,카드,80000,의정활동 및 직무수행 소요경비,3,NaN,NaN,금
3066,도봉구,NaN,의장,2018-02-26 00:00:00,13:29:47,NaN,NaN,카드,186000,제43호 도봉의회보 발간에 따른 간담회,7,NaN,NaN,월
3111,도봉구,NaN,부의장,2018-02-26 00:00:00,20:49:50,NaN,NaN,카드,89000,의정활동 및 직무수행 소요경비,3,NaN,NaN,월
3210,도봉구,NaN,복지건설위원장,2018-02-26 00:00:00,13:45:11,NaN,NaN,카드,11000,의정활동 및 직무수행 소요경비,2,NaN,NaN,월
3067,도봉구,NaN,의장,2018-02-26 00:00:00,19:09:12,NaN,NaN,카드,92000,의정활동 및 직무수행 소요경비,6,NaN,NaN,월
3112,도봉구,NaN,부의장,2018-02-27 00:00:00,19:11:42,NaN,NaN,카드,294000,제274회 임시회 상임위 활동 지원 관련 간담회 개최,10,NaN,NaN,화
3173,도봉구,NaN,복지건설위원장,2018-02-27 00:00:00,20:05:38,NaN,NaN,카드,95000,의정 정보교류 소요경비,4,NaN,NaN,화
3151,도봉구,NaN,행정기획위원장,2018-02-27 00:00:00,13:04:57,NaN,NaN,카드,168000,제274회 상임위원회 준비 관련 간담회,6,NaN,NaN,화
3152,도봉구,NaN,운영위원장,2018-02-27 00:00:00,20:18:11,NaN,NaN,카드,162000,2018년 의장 표창 심사위원회 구성 관련 간담회,6,NaN,NaN,화
3068,도봉구,NaN,의장,2018-02-27 00:00:00,13:46:15,NaN,NaN,카드,198000,의정 정보교류 소요경비,7,NaN,NaN,화
3166,도봉구,NaN,운영위원장,2018-02-27 00:00:00,13:53:48,NaN,NaN,카드,120000,지방의회 알기 체험학습 프로그램 활성화 방안 관련 간담회,5,NaN,NaN,화
3069,도봉구,NaN,의장,2018-02-28 00:00:00,21:31:31,NaN,NaN,카드,198000,제274회 임시회 개최 준비 관련 간담회,7,NaN,NaN,수
3198,도봉구,NaN,복지건설위원장,2018-02-28 00:00:00,14:31:51,NaN,NaN,카드,28000,의정활동 및 직무수행 소요경비,3,NaN,NaN,수
3114,도봉구,NaN,부의장,2018-02-28 00:00:00,21:02:13,NaN,NaN,카드,12000,의정활동 및 직무수행 소요경비,2,NaN,NaN,수
3113,도봉구,NaN,부의장,2018-02-28 00:00:00,12:59:30,NaN,NaN,카드,108000,의정 정보교류 소요경비,4,NaN,NaN,수
3194,도봉구,NaN,운영위원장,2018-02-28 00:00:00,12:51:56,NaN,NaN,카드,33000,의정활동 및 직무수행 소요경비,3,NaN,NaN,수
3179,도봉구,NaN,행정기획위원장,2018-02-28 00:00:00,19:32:14,NaN,NaN,카드,72000,의정 정보교류 소요경비,3,NaN,NaN,수
3165,도봉구,NaN,운영위원장,2018-02-28 00:00:00,21:57:26,NaN,NaN,카드,121000,의정 정보교류 소요경비,5,NaN,NaN,수

## 꺽기

In [16]:
for 임시_구청이름, 각_프레임 in 구청별.items():
    각_프레임.시분값 = 각_프레임.시분값.astype(str)
    구분 =list(set(각_프레임.구분))
    직접확인_프레임 = pd.DataFrame(columns=칼럼)
    간접확인_프레임 = pd.DataFrame(columns=칼럼)
    for 임시_구분_이름 in 구분:
        임시_구분 =각_프레임[각_프레임.구분 == 임시_구분_이름]
        일시별_금액합계 =임시_구분.groupby('집행일시').sum()
        임시_프레임 =pd.DataFrame(columns=칼럼)
        for 임시_일시 in list(일시별_금액합계[일시별_금액합계.집행금액 >300000].index):
            #print(각_프레임[각_프레임.집행일시 == i])
            임시_프레임 =각_프레임[각_프레임.집행일시 == 임시_일시]
            임시_프레임 = 임시_프레임[임시_프레임.구분 ==임시_구분_이름]
            직접확인_프레임 =직접확인_프레임.append(임시_프레임)  #뽑힌거 일단 모두 저장

        임시_장소종류 = set(임시_프레임.집행장소)
        for 임시_장소 in 임시_장소종류:
            if 임시_프레임[임시_프레임.집행장소 == 임시_장소].집행일시.count() > 1:
                간접확인_프레임 = 간접확인_프레임.append(임시_프레임[임시_프레임.집행장소 == 임시_장소])
    if not 직접확인_프레임.empty:
        직접확인_프레임.to_excel(r"C:/Users/user/Desktop/구청별 업무추진비(엑셀)/꺽기/하루에_일정비용이상사용_직접확인필요/"+임시_구청이름+"_30만원이상.xlsx")
    if not 간접확인_프레임.empty:
        간접확인_프레임.to_excel(r"C:/Users/user/Desktop/구청별 업무추진비(엑셀)/꺽기/하루에_일정비용이상사용_상호명같은것만분류/"+임시_구청이름+"_30만원이상.xlsx")

KeyboardInterrupt:

In [13]:
for 임시_구청이름, 각_프레임 in 구청별.items():
    각_프레임.시분값 = 각_프레임.시분값.astype(str)
    구분 =list(set(각_프레임.구분))
    직접확인_프레임 = pd.DataFrame(columns=칼럼)
    간접확인_프레임 = pd.DataFrame(columns=칼럼)
    for 임시_구분_이름 in 구분:
        임시_구분 =각_프레임[각_프레임.구분 == 임시_구분_이름]
        일시별_금액합계 =임시_구분.groupby('집행일시').sum()
        임시_프레임 =pd.DataFrame(columns=칼럼)
        for 임시_일시 in list(일시별_금액합계[일시별_금액합계.집행금액 >500000].index):
            #print(각_프레임[각_프레임.집행일시 == i])
            임시_프레임 =각_프레임[각_프레임.집행일시 == 임시_일시]
            임시_프레임 = 임시_프레임[임시_프레임.구분 ==임시_구분_이름]
            직접확인_프레임 =직접확인_프레임.append(임시_프레임)  #뽑힌거 일단 모두 저장

        임시_장소종류 = set(임시_프레임.집행장소)
        for 임시_장소 in 임시_장소종류:
            if 임시_프레임[임시_프레임.집행장소 == 임시_장소].집행일시.count() > 1:
                간접확인_프레임 = 간접확인_프레임.append(임시_프레임[임시_프레임.집행장소 == 임시_장소])
    if not 직접확인_프레임.empty:
        직접확인_프레임.to_excel(r"C:/Users/user/Desktop/구청별 업무추진비(엑셀)/꺽기/하루에_일정비용이상사용_직접확인필요/"+임시_구청이름+"_50만원이상.xlsx")
    if not 간접확인_프레임.empty:
        간접확인_프레임.to_excel(r"C:/Users/user/Desktop/구청별 업무추진비(엑셀)/꺽기/하루에_일정비용이상사용_상호명같은것만분류/"+임시_구청이름+"_50만원이상.xlsx")

## 휴일이용

In [31]:
for 임시_구청이름, 각_프레임 in 구청별.items():
    각_프레임[(각_프레임.요일 =='일') | (각_프레임.요일 =='토')].to_excel(파일위치경로+'/휴일사용//'+임시_구청이름+'(토_일).xlsx')

In [32]:
휴일이용_프레임 =pd.DataFrame(index =['금', '목', '수', '월', '일', '토', '화', '휴일이용비율', '합계'])
for 임시_구청이름, 각_프레임 in 구청별.items():
    임시_프레임 =각_프레임.groupby('요일')['자치구'].count()
    임시_합계 =임시_프레임.sum()
    임시_일 = 0
    임시_토 = 0
    try:
        임시_토 = 임시_프레임['토']
    except KeyError:
        pass
    try:
        임시_일 = 임시_프레임['일']
    except KeyError:
        pass
    임시_프레임['휴일이용비율'] = (임시_토+임시_일) / 임시_합계
    임시_프레임['합계']=임시_합계
    임시_프레임.name = 임시_구청이름
    휴일이용_프레임[임시_구청이름] = 임시_프레임
휴일이용_프레임.to_excel(파일위치경로+'/휴일사용//구청별_휴일이용비율.xlsx')

In [33]:
휴일이용_프레임

,종로구,중구,용산구,성동구,광진구,동대문구,중랑구,성북구,강북구,도봉구,...,강서구,구로구,금천구,영등포구,동작구,관악구,서초구,강남구,송파구,강동구
금,487.000000,879.000000,916.00000,494.000000,648.000000,549.00000,639.000000,637.0,758.000000,637.000000,...,544.000000,726.000000,816.000000,553.000000,514.000000,611.000000,630.000000,531.000000,801.000000,179.000000
목,496.000000,924.000000,901.00000,539.000000,702.000000,565.00000,612.000000,616.0,818.000000,649.000000,...,590.000000,621.000000,786.000000,502.000000,566.000000,618.000000,634.000000,580.000000,740.000000,178.000000
수,507.000000,829.000000,946.00000,549.000000,641.000000,574.00000,635.000000,653.0,727.000000,575.000000,...,527.000000,727.000000,752.000000,503.000000,548.000000,615.000000,669.000000,617.000000,676.000000,186.000000
월,511.000000,889.000000,924.00000,562.000000,800.000000,625.00000,628.000000,689.0,782.000000,647.000000,...,572.000000,707.000000,749.000000,538.000000,547.000000,635.000000,636.000000,586.000000,746.000000,152.000000
일,167.000000,222.000000,604.00000,36.000000,5.000000,29.00000,109.000000,NaN,249.000000,10.000000,...,78.000000,405.000000,255.000000,21.000000,202.000000,316.000000,319.000000,1.000000,46.000000,150.000000
토,291.000000,371.000000,708.00000,91.000000,209.000000,74.00000,239.000000,NaN,428.000000,29.000000,...,254.000000,460.000000,397.000000,59.000000,289.000000,435.000000,420.000000,10.000000,77.000000,145.000000
화,512.000000,923.000000,904.00000,572.000000,633.000000,609.00000,612.000000,674.0,788.000000,622.000000,...,563.000000,612.000000,787.000000,499.000000,574.000000,564.000000,653.000000,575.000000,720.000000,210.000000
휴일이용비율,0.154157,0.117729,0.22226,0.044671,0.058824,0.03405,0.100173,0.0,0.148791,0.012307,...,0.106138,0.203147,0.143549,0.029907,0.151543,0.197944,0.186569,0.003793,0.032317,0.245833
합계,2971.000000,5037.000000,5903.00000,2843.000000,3638.000000,3025.00000,3474.000000,3269.0,4550.000000,3169.000000,...,3128.000000,4258.000000,4542.000000,2675.000000,3240.000000,3794.000000,3961.000000,2900.000000,3806.000000,1200.000000

In [67]:
평일_주말_합계액 = pd.DataFrame(index=['평일','주말'])
for 임시_구청이름, 각_프레임  in 구청별.items():
    임시 = 각_프레임.groupby('요일')
    try:
        임시_주말_토 = 임시.sum()['집행금액'].loc['토']
    except KeyError:
        임시_주말_토 = 0
    try:
        임시_주말_일 = 임시.sum()['집행금액'].loc['일']
    except KeyError:
        임시_주말_일 = 0
    임시_주말 = 임시_주말_토+임시_주말_일
    임시_평일 = 임시.sum()['집행금액'].loc[['월','화','수','목','금']].sum()
    평일_주말_합계액[임시_구청이름] = [임시_평일,임시_주말]
    평일_주말_합계액

In [78]:
평일_주말_합계액.loc['합계'] = 평일_주말_합계액.sum()
평일_주말_합계액.T.to_excel(파일위치경로+'/휴일사용/평일_주말_합계액.xlsx')

In [83]:
구청별['성북구'][구청별['성북구'].요일 == '일']

Empty DataFrame
Columns: [자치구, 담당, 구분, 집행일시, 시분값, 집행장소, 집행주소, 결재방법, 집행금액, 집행목적/집행내역/내용, 대상인원, 50만원이상 결재시 증빙서류, 비고, 요일]
Index: []